apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-pod
          image: demo:2
          ports:
          - containerPort: 5000
  selector:
    matchLabels:
      app: demo